# Generated by Django 3.2.9 on 2021-11-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=' ', max_length=50)),
                ('Descripton', models.CharField(default=' ', max_length=300)),
                ('publish_date', models.DateField()),
                ('category', models.CharField(default=' ', max_length=50)),
                ('sub_catagory', models.CharField(default=' ', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default=' ', upload_to='shop')),
            ],
        ),
    ]
