# Generated by Django 3.2.9 on 2021-11-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211105_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_catagory',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
