# Generated by Django 3.2.9 on 2021-11-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211105_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=' ', upload_to='shop/images'),
        ),
    ]
