# Generated by Django 3.2.9 on 2021-11-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
